#pragma once
#ifdef PKMDS_CMAKE_USED
#include <pkmds/pkmds_g5.h>
#else
#include "../../include/pkmds/pkmds_g5.h"
#endif
namespace Species_g6
{
enum pkxspecies : uint16
{
    NOTHING,
    bulbasaur,
    ivysaur,
    venusaur,
    charmander,
    charmeleon,
    charizard,
    squirtle,
    wartortle,
    blastoise,
    caterpie,
    metapod,
    butterfree,
    weedle,
    kakuna,
    beedrill,
    pidgey,
    pidgeotto,
    pidgeot,
    rattata,
    raticate,
    spearow,
    fearow,
    ekans,
    arbok,
    pikachu,
    raichu,
    sandshrew,
    sandslash,
    nidoran_f,
    nidorina,
    nidoqueen,
    nidoran_m,
    nidorino,
    nidoking,
    clefairy,
    clefable,
    vulpix,
    ninetales,
    jigglypuff,
    wigglytuff,
    zubat,
    golbat,
    oddish,
    gloom,
    vileplume,
    paras,
    parasect,
    venonat,
    venomoth,
    diglett,
    dugtrio,
    meowth,
    persian,
    psyduck,
    golduck,
    mankey,
    primeape,
    growlithe,
    arcanine,
    poliwag,
    poliwhirl,
    poliwrath,
    abra,
    kadabra,
    alakazam,
    machop,
    machoke,
    machamp,
    bellsprout,
    weepinbell,
    victreebel,
    tentacool,
    tentacruel,
    geodude,
    graveler,
    golem,
    ponyta,
    rapidash,
    slowpoke,
    slowbro,
    magnemite,
    magneton,
    farfetch_d,
    doduo,
    dodrio,
    seel,
    dewgong,
    grimer,
    muk,
    shellder,
    cloyster,
    gastly,
    haunter,
    gengar,
    onix,
    drowzee,
    hypno,
    krabby,
    kingler,
    voltorb,
    electrode,
    exeggcute,
    exeggutor,
    cubone,
    marowak,
    hitmonlee,
    hitmonchan,
    lickitung,
    koffing,
    weezing,
    rhyhorn,
    rhydon,
    chansey,
    tangela,
    kangaskhan,
    horsea,
    seadra,
    goldeen,
    seaking,
    staryu,
    starmie,
    mr_mime,
    scyther,
    jynx,
    electabuzz,
    magmar,
    pinsir,
    tauros,
    magikarp,
    gyarados,
    lapras,
    ditto,
    eevee,
    vaporeon,
    jolteon,
    flareon,
    porygon,
    omanyte,
    omastar,
    kabuto,
    kabutops,
    aerodactyl,
    snorlax,
    articuno,
    zapdos,
    moltres,
    dratini,
    dragonair,
    dragonite,
    mewtwo,
    mew,
    chikorita,
    bayleef,
    meganium,
    cyndaquil,
    quilava,
    typhlosion,
    totodile,
    croconaw,
    feraligatr,
    sentret,
    furret,
    hoothoot,
    noctowl,
    ledyba,
    ledian,
    spinarak,
    ariados,
    crobat,
    chinchou,
    lanturn,
    pichu,
    cleffa,
    igglybuff,
    togepi,
    togetic,
    natu,
    xatu,
    mareep,
    flaaffy,
    ampharos,
    bellossom,
    marill,
    azumarill,
    sudowoodo,
    politoed,
    hoppip,
    skiploom,
    jumpluff,
    aipom,
    sunkern,
    sunflora,
    yanma,
    wooper,
    quagsire,
    espeon,
    umbreon,
    murkrow,
    slowking,
    misdreavus,
    unown,
    wobbuffet,
    girafarig,
    pineco,
    forretress,
    dunsparce,
    gligar,
    steelix,
    snubbull,
    granbull,
    qwilfish,
    scizor,
    shuckle,
    heracross,
    sneasel,
    teddiursa,
    ursaring,
    slugma,
    magcargo,
    swinub,
    piloswine,
    corsola,
    remoraid,
    octillery,
    delibird,
    mantine,
    skarmory,
    houndour,
    houndoom,
    kingdra,
    phanpy,
    donphan,
    porygon2,
    stantler,
    smeargle,
    tyrogue,
    hitmontop,
    smoochum,
    elekid,
    magby,
    miltank,
    blissey,
    raikou,
    entei,
    suicune,
    larvitar,
    pupitar,
    tyranitar,
    lugia,
    ho_oh,
    celebi,
    treecko,
    grovyle,
    sceptile,
    torchic,
    combusken,
    blaziken,
    mudkip,
    marshtomp,
    swampert,
    poochyena,
    mightyena,
    zigzagoon,
    linoone,
    wurmple,
    silcoon,
    beautifly,
    cascoon,
    dustox,
    lotad,
    lombre,
    ludicolo,
    seedot,
    nuzleaf,
    shiftry,
    taillow,
    swellow,
    wingull,
    pelipper,
    ralts,
    kirlia,
    gardevoir,
    surskit,
    masquerain,
    shroomish,
    breloom,
    slakoth,
    vigoroth,
    slaking,
    nincada,
    ninjask,
    shedinja,
    whismur,
    loudred,
    exploud,
    makuhita,
    hariyama,
    azurill,
    nosepass,
    skitty,
    delcatty,
    sableye,
    mawile,
    aron,
    lairon,
    aggron,
    meditite,
    medicham,
    electrike,
    manectric,
    plusle,
    minun,
    volbeat,
    illumise,
    roselia,
    gulpin,
    swalot,
    carvanha,
    sharpedo,
    wailmer,
    wailord,
    numel,
    camerupt,
    torkoal,
    spoink,
    grumpig,
    spinda,
    trapinch,
    vibrava,
    flygon,
    cacnea,
    cacturne,
    swablu,
    altaria,
    zangoose,
    seviper,
    lunatone,
    solrock,
    barboach,
    whiscash,
    corphish,
    crawdaunt,
    baltoy,
    claydol,
    lileep,
    cradily,
    anorith,
    armaldo,
    feebas,
    milotic,
    castform,
    kecleon,
    shuppet,
    banette,
    duskull,
    dusclops,
    tropius,
    chimecho,
    absol,
    wynaut,
    snorunt,
    glalie,
    spheal,
    sealeo,
    walrein,
    clamperl,
    huntail,
    gorebyss,
    relicanth,
    luvdisc,
    bagon,
    shelgon,
    salamence,
    beldum,
    metang,
    metagross,
    regirock,
    regice,
    registeel,
    latias,
    latios,
    kyogre,
    groudon,
    rayquaza,
    jirachi,
    deoxys,
    turtwig,
    grotle,
    torterra,
    chimchar,
    monferno,
    infernape,
    piplup,
    prinplup,
    empoleon,
    starly,
    staravia,
    staraptor,
    bidoof,
    bibarel,
    kricketot,
    kricketune,
    shinx,
    luxio,
    luxray,
    budew,
    roserade,
    cranidos,
    rampardos,
    shieldon,
    bastiodon,
    burmy,
    wormadam,
    mothim,
    combee,
    vespiquen,
    pachirisu,
    buizel,
    floatzel,
    cherubi,
    cherrim,
    shellos,
    gastrodon,
    ambipom,
    drifloon,
    drifblim,
    buneary,
    lopunny,
    mismagius,
    honchkrow,
    glameow,
    purugly,
    chingling,
    stunky,
    skuntank,
    bronzor,
    bronzong,
    bonsly,
    mime_jr,
    happiny,
    chatot,
    spiritomb,
    gible,
    gabite,
    garchomp,
    munchlax,
    riolu,
    lucario,
    hippopotas,
    hippowdon,
    skorupi,
    drapion,
    croagunk,
    toxicroak,
    carnivine,
    finneon,
    lumineon,
    mantyke,
    snover,
    abomasnow,
    weavile,
    magnezone,
    lickilicky,
    rhyperior,
    tangrowth,
    electivire,
    magmortar,
    togekiss,
    yanmega,
    leafeon,
    glaceon,
    gliscor,
    mamoswine,
    porygon_z,
    gallade,
    probopass,
    dusknoir,
    froslass,
    rotom,
    uxie,
    mesprit,
    azelf,
    dialga,
    palkia,
    heatran,
    regigigas,
    giratina,
    cresselia,
    phione,
    manaphy,
    darkrai,
    shaymin,
    arceus,
    victini,
    snivy,
    servine,
    serperior,
    tepig,
    pignite,
    emboar,
    oshawott,
    dewott,
    samurott,
    patrat,
    watchog,
    lillipup,
    herdier,
    stoutland,
    purrloin,
    liepard,
    pansage,
    simisage,
    pansear,
    simisear,
    panpour,
    simipour,
    munna,
    musharna,
    pidove,
    tranquill,
    unfezant,
    blitzle,
    zebstrika,
    roggenrola,
    boldore,
    gigalith,
    woobat,
    swoobat,
    drilbur,
    excadrill,
    audino,
    timburr,
    gurdurr,
    conkeldurr,
    tympole,
    palpitoad,
    seismitoad,
    throh,
    sawk,
    sewaddle,
    swadloon,
    leavanny,
    venipede,
    whirlipede,
    scolipede,
    cottonee,
    whimsicott,
    petilil,
    lilligant,
    basculin,
    sandile,
    krokorok,
    krookodile,
    darumaka,
    darmanitan,
    maractus,
    dwebble,
    crustle,
    scraggy,
    scrafty,
    sigilyph,
    yamask,
    cofagrigus,
    tirtouga,
    carracosta,
    archen,
    archeops,
    trubbish,
    garbodor,
    zorua,
    zoroark,
    minccino,
    cinccino,
    gothita,
    gothorita,
    gothitelle,
    solosis,
    duosion,
    reuniclus,
    ducklett,
    swanna,
    vanillite,
    vanillish,
    vanilluxe,
    deerling,
    sawsbuck,
    emolga,
    karrablast,
    escavalier,
    foongus,
    amoonguss,
    frillish,
    jellicent,
    alomomola,
    joltik,
    galvantula,
    ferroseed,
    ferrothorn,
    klink,
    klang,
    klinklang,
    tynamo,
    eelektrik,
    eelektross,
    elgyem,
    beheeyem,
    litwick,
    lampent,
    chandelure,
    axew,
    fraxure,
    haxorus,
    cubchoo,
    beartic,
    cryogonal,
    shelmet,
    accelgor,
    stunfisk,
    mienfoo,
    mienshao,
    druddigon,
    golett,
    golurk,
    pawniard,
    bisharp,
    bouffalant,
    rufflet,
    braviary,
    vullaby,
    mandibuzz,
    heatmor,
    durant,
    deino,
    zweilous,
    hydreigon,
    larvesta,
    volcarona,
    cobalion,
    terrakion,
    virizion,
    tornadus,
    thundurus,
    reshiram,
    zekrom,
    landorus,
    kyurem,
    keldeo,
    meloetta,
    genesect,
    chespin,
    quilladin,
    chesnaught,
    fennekin,
    braixen,
    delphox,
    froakie,
    frogadier,
    greninja,
    bunnelby,
    diggersby,
    fletchling,
    fletchinder,
    talonflame,
    scatterbug,
    spewpa,
    vivillon,
    litleo,
    pyroar,
    flabebe,
    floette,
    florges,
    skiddo,
    gogoat,
    pancham,
    pangoro,
    furfrou,
    espurr,
    meowstic,
    honedge,
    doublade,
    aegislash,
    spritzee,
    aromatisse,
    swirlix,
    slurpuff,
    inkay,
    malamar,
    binacle,
    barbaracle,
    skrelp,
    dragalge,
    clauncher,
    clawitzer,
    helioptile,
    heliolisk,
    tyrunt,
    tyrantrum,
    amaura,
    aurorus,
    sylveon,
    hawlucha,
    dedenne,
    carbink,
    goomy,
    sliggoo,
    goodra,
    klefki,
    phantump,
    trevenant,
    pumpkaboo,
    gourgeist,
    bergmite,
    avalugg,
    noibat,
    noivern,
    xerneas,
    yveltal,
    zygarde,
    diancie,
    volcanion,
    hoopa,
    bad_egg
};
}
namespace Moves_g6
{
enum moves : uint16
{
    NOTHING,
    pound,
    karatechop,
    doubleslap,
    cometpunch,
    megapunch,
    payday,
    firepunch,
    icepunch,
    thunderpunch,
    scratch,
    vicegrip,
    guillotine,
    razorwind,
    swordsdance,
    cut,
    gust,
    wingattack,
    whirlwind,
    fly,
    bind,
    slam,
    vinewhip,
    stomp,
    doublekick,
    megakick,
    jumpkick,
    rollingkick,
    sandattack,
    headbutt,
    hornattack,
    furyattack,
    horndrill,
    tackle,
    bodyslam,
    wrap,
    takedown,
    thrash,
    doubleedge,
    tailwhip,
    poisonsting,
    twineedle,
    pinmissile,
    leer,
    bite,
    growl,
    roar,
    sing,
    supersonic,
    sonicboom,
    disable,
    acid,
    ember,
    flamethrower,
    mist,
    watergun,
    hydropump,
    surf,
    icebeam,
    blizzard,
    psybeam,
    bubblebeam,
    aurorabeam,
    hyperbeam,
    peck,
    drillpeck,
    submission,
    lowkick,
    counter,
    seismictoss,
    strength,
    absorb,
    megadrain,
    leechseed,
    growth,
    razorleaf,
    solarbeam,
    poisonpowder,
    stunspore,
    sleeppowder,
    petaldance,
    stringshot,
    dragonrage,
    firespin,
    thundershock,
    thunderbolt,
    thunderwave,
    thunder,
    rockthrow,
    earthquake,
    fissure,
    dig,
    toxic,
    confusion,
    psychic,
    hypnosis,
    meditate,
    agility,
    quickattack,
    rage,
    teleport,
    nightshade,
    mimic,
    screech,
    doubleteam,
    recover,
    harden,
    minimize,
    smokescreen,
    confuseray,
    withdraw,
    defensecurl,
    barrier,
    lightscreen,
    haze,
    reflect,
    focusenergy,
    bide,
    metronome,
    mirrormove,
    selfdestruct,
    eggbomb,
    lick,
    smog,
    sludge,
    boneclub,
    fireblast,
    waterfall,
    clamp,
    swift,
    skullbash,
    spikecannon,
    constrict,
    amnesia,
    kinesis,
    softboiled,
    hijumpkick,
    glare,
    dreameater,
    poisongas,
    barrage,
    leechlife,
    lovelykiss,
    skyattack,
    transform,
    bubble,
    dizzypunch,
    spore,
    flash,
    psywave,
    splash,
    acidarmor,
    crabhammer,
    explosion,
    furyswipes,
    bonemerang,
    rest,
    rockslide,
    hyperfang,
    sharpen,
    conversion,
    triattack,
    superfang,
    slash,
    substitute,
    struggle,
    sketch,
    triplekick,
    thief,
    spiderweb,
    mindreader,
    nightmare,
    flamewheel,
    snore,
    curse,
    flail,
    conversion2,
    aeroblast,
    cottonspore,
    reversal,
    spite,
    powdersnow,
    protect,
    machpunch,
    scaryface,
    faintattack,
    sweetkiss,
    bellydrum,
    sludgebomb,
    mudslap,
    octazooka,
    spikes,
    zapcannon,
    foresight,
    destinybond,
    perishsong,
    icywind,
    detect,
    bonerush,
    lockon,
    outrage,
    sandstorm,
    gigadrain,
    endure,
    charm,
    rollout,
    falseswipe,
    swagger,
    milkdrink,
    spark,
    furycutter,
    steelwing,
    meanlook,
    attract,
    sleeptalk,
    healbell,
    return_,
    present,
    frustration,
    safeguard,
    painsplit,
    sacredfire,
    magnitude,
    dynamicpunch,
    megahorn,
    dragonbreath,
    batonpass,
    encore,
    pursuit,
    rapidspin,
    sweetscent,
    irontail,
    metalclaw,
    vitalthrow,
    morningsun,
    synthesis,
    moonlight,
    hiddenpower,
    crosschop,
    twister,
    raindance,
    sunnyday,
    crunch,
    mirrorcoat,
    psychup,
    extremespeed,
    ancientpower,
    shadowball,
    futuresight,
    rocksmash,
    whirlpool,
    beatup,
    fakeout,
    uproar,
    stockpile,
    spitup,
    swallow,
    heatwave,
    hail,
    torment,
    flatter,
    willowisp,
    memento,
    facade,
    focuspunch,
    smellingsalt,
    followme,
    naturepower,
    charge,
    taunt,
    helpinghand,
    trick,
    roleplay,
    wish,
    assist,
    ingrain,
    superpower,
    magiccoat,
    recycle,
    revenge,
    brickbreak,
    yawn,
    knockoff,
    endeavor,
    eruption,
    skillswap,
    imprison,
    refresh,
    grudge,
    snatch,
    secretpower,
    dive,
    armthrust,
    camouflage,
    tailglow,
    lusterpurge,
    mistball,
    featherdance,
    teeterdance,
    blazekick,
    mudsport,
    iceball,
    needlearm,
    slackoff,
    hypervoice,
    poisonfang,
    crushclaw,
    blastburn,
    hydrocannon,
    meteormash,
    astonish,
    weatherball,
    aromatherapy,
    faketears,
    aircutter,
    overheat,
    odorsleuth,
    rocktomb,
    silverwind,
    metalsound,
    grasswhistle,
    tickle,
    cosmicpower,
    waterspout,
    signalbeam,
    shadowpunch,
    extrasensory,
    skyuppercut,
    sandtomb,
    sheercold,
    muddywater,
    bulletseed,
    aerialace,
    iciclespear,
    irondefense,
    block,
    howl,
    dragonclaw,
    frenzyplant,
    bulkup,
    bounce,
    mudshot,
    poisontail,
    covet,
    volttackle,
    magicalleaf,
    watersport,
    calmmind,
    leafblade,
    dragondance,
    rockblast,
    shockwave,
    waterpulse,
    doomdesire,
    psychoboost,
    roost,
    gravity,
    miracleeye,
    wakeupslap,
    hammerarm,
    gyroball,
    healingwish,
    brine,
    naturalgift,
    feint,
    pluck,
    tailwind,
    acupressure,
    metalburst,
    uturn,
    closecombat,
    payback,
    assurance,
    embargo,
    fling,
    psychoshift,
    trumpcard,
    healblock,
    wringout,
    powertrick,
    gastroacid,
    luckychant,
    mefirst,
    copycat,
    powerswap,
    guardswap,
    punishment,
    lastresort,
    worryseed,
    suckerpunch,
    toxicspikes,
    heartswap,
    aquaring,
    magnetrise,
    flareblitz,
    forcepalm,
    aurasphere,
    rockpolish,
    poisonjab,
    darkpulse,
    nightslash,
    aquatail,
    seedbomb,
    airslash,
    xscissor,
    bugbuzz,
    dragonpulse,
    dragonrush,
    powergem,
    drainpunch,
    vacuumwave,
    focusblast,
    energyball,
    bravebird,
    earthpower,
    switcheroo,
    gigaimpact,
    nastyplot,
    bulletpunch,
    avalanche,
    iceshard,
    shadowclaw,
    thunderfang,
    icefang,
    firefang,
    shadowsneak,
    mudbomb,
    psychocut,
    zenheadbutt,
    mirrorshot,
    flashcannon,
    rockclimb,
    defog,
    trickroom,
    dracometeor,
    discharge,
    lavaplume,
    leafstorm,
    powerwhip,
    rockwrecker,
    crosspoison,
    gunkshot,
    ironhead,
    magnetbomb,
    stoneedge,
    captivate,
    stealthrock,
    grassknot,
    chatter,
    judgment,
    bugbite,
    chargebeam,
    woodhammer,
    aquajet,
    attackorder,
    defendorder,
    healorder,
    headsmash,
    doublehit,
    roaroftime,
    spacialrend,
    lunardance,
    crushgrip,
    magmastorm,
    darkvoid,
    seedflare,
    ominouswind,
    shadowforce,
    honeclaws,
    wideguard,
    guardsplit,
    powersplit,
    wonderroom,
    psyshock,
    venoshock,
    autotomize,
    ragepowder,
    telekinesis,
    magicroom,
    smackdown,
    stormthrow,
    flameburst,
    sludgewave,
    quiverdance,
    heavyslam,
    synchronoise,
    electroball,
    soak,
    flamecharge,
    coil,
    lowsweep,
    acidspray,
    foulplay,
    simplebeam,
    entrainment,
    afteryou,
    round,
    echoedvoice,
    chipaway,
    clearsmog,
    storedpower,
    quickguard,
    allyswitch,
    scald,
    shellsmash,
    healpulse,
    hex,
    skydrop,
    shiftgear,
    circlethrow,
    incinerate,
    quash,
    acrobatics,
    reflecttype,
    retaliate,
    finalgambit,
    bestow,
    inferno,
    waterpledge,
    firepledge,
    grasspledge,
    voltswitch,
    strugglebug,
    bulldoze,
    frostbreath,
    dragontail,
    workup,
    electroweb,
    wildcharge,
    drillrun,
    dualchop,
    heartstamp,
    hornleech,
    sacredsword,
    razorshell,
    heatcrash,
    leaftornado,
    steamroller,
    cottonguard,
    nightdaze,
    psystrike,
    tailslap,
    hurricane,
    headcharge,
    geargrind,
    searingshot,
    technoblast,
    relicsong,
    secretsword,
    glaciate,
    boltstrike,
    blueflare,
    fierydance,
    freezeshock,
    iceburn,
    snarl,
    iciclecrash,
    vcreate,
    fusionflare,
    fusionbolt,
    flyingpress=560,
    matblock=561,
    belch=562,
    rototiller=563,
    stickyweb=564,
    fellstinger=565,
    phantomforce=566,
    trickortreat=567,
    nobleroar=568,
    iondeluge=569,
    paraboliccharge=570,
    forestscurse=571,
    petalblizzard=572,
    freezedry=573,
    disarmingvoice=574,
    partingshot=575,
    topsyturvy=576,
    drainingkiss=577,
    craftyshield=578,
    flowershield=579,
    grassyterrain=580,
    mistyterrain=581,
    electrify=582,
    playrough=583,
    fairywind=584,
    moonblast=585,
    boomburst=586,
    fairylock=587,
    kingsshield=588,
    playnice=589,
    confide=590,
    watershuriken=594,
    mysticalfire=595,
    spikyshield=596,
    aromaticmist=597,
    eerieimpulse=598,
    venomdrench=599,
    powder=600,
    geomancy=601,
    magneticflux=602,
    happyhour=603,
    electricterrain=604,
    dazzlinggleam=605,
    celebrate=606,
    babydolleyes=608,
    nuzzle=609,
    infestation=611,
    poweruppunch=612,
    oblivionwing=613,
    landswrath=616
};
}
namespace Abilities_g6
{
enum abilities : byte
{
    NOTHING,
    stench,
    drizzle,
    speedboost,
    battlearmor,
    sturdy,
    damp,
    limber,
    sandveil,
    static_,
    voltabsorb,
    waterabsorb,
    oblivious,
    cloudnine,
    compoundeyes,
    insomnia,
    colorchange,
    immunity,
    flashfire,
    shielddust,
    owntempo,
    suctioncups,
    intimidate,
    shadowtag,
    roughskin,
    wonderguard,
    levitate,
    effectspore,
    synchronize,
    clearbody,
    naturalcure,
    lightningrod,
    serenegrace,
    swiftswim,
    chlorophyll,
    illuminate,
    trace,
    hugepower,
    poisonpoint,
    innerfocus,
    magmaarmor,
    waterveil,
    magnetpull,
    soundproof,
    raindish,
    sandstream,
    pressure,
    thickfat,
    earlybird,
    flamebody,
    runaway,
    keeneye,
    hypercutter,
    pickup,
    truant,
    hustle,
    cutecharm,
    plus,
    minus,
    forecast,
    stickyhold,
    shedskin,
    guts,
    marvelscale,
    liquidooze,
    overgrow,
    blaze,
    torrent,
    swarm,
    rockhead,
    drought,
    arenatrap,
    vitalspirit,
    whitesmoke,
    purepower,
    shellarmor,
    airlock,
    tangledfeet,
    motordrive,
    rivalry,
    steadfast,
    snowcloak,
    gluttony,
    angerpoint,
    unburden,
    heatproof,
    simple,
    dryskin,
    download,
    ironfist,
    poisonheal,
    adaptability,
    skilllink,
    hydration,
    solarpower,
    quickfeet,
    normalize,
    sniper,
    magicguard,
    noguard,
    stall,
    technician,
    leafguard,
    klutz,
    moldbreaker,
    superluck,
    aftermath,
    anticipation,
    forewarn,
    unaware,
    tintedlens,
    filter,
    slowstart,
    scrappy,
    stormdrain,
    icebody,
    solidrock,
    snowwarning,
    honeygather,
    frisk,
    reckless,
    multitype,
    flowergift,
    baddreams,
    pickpocket,
    sheerforce,
    contrary,
    unnerve,
    defiant,
    defeatist,
    cursedbody,
    healer,
    friendguard,
    weakarmor,
    heavymetal,
    lightmetal,
    multiscale,
    toxicboost,
    flareboost,
    harvest,
    telepathy,
    moody,
    overcoat,
    poisontouch,
    regenerator,
    bigpecks,
    sandrush,
    wonderskin,
    analytic,
    illusion,
    imposter,
    infiltrator,
    mummy,
    moxie,
    justified,
    rattled,
    magicbounce,
    sapsipper,
    prankster,
    sandforce,
    ironbarbs,
    zenmode,
    victorystar,
    turboblaze,
    teravolt,
    aromaveil=165,
    flowerveil=166,
    cheekpouch=167,
    protean=168,
    furcoat=169,
    magician=170,
    bulletproof=171,
    competitive=172,
    strongjaw=173,
    refrigerate=174,
    sweetveil=175,
    stancechange=176,
    galewings=177,
    megalauncher=178,
    grasspelt=179,
    symbiosis=180,
    toughclaws=181,
    pixilate=182,
    gooey=183,
    darkaura=186,
    fairyaura=187,
    aurabreak=188,
};
}
namespace Items_g6
{
enum items : uint16
{
    NOTHING =  0x0000,
    masterball =  0x0001,
    ultraball =  0x0002,
    greatball =  0x0003,
    pokeball =  0x0004,
    safariball =  0x0005,
    netball =  0x0006,
    diveball =  0x0007,
    nestball =  0x0008,
    repeatball =  0x0009,
    timerball =  0x000a,
    luxuryball =  0x000b,
    premierball =  0x000c,
    duskball =  0x000d,
    healball =  0x000e,
    quickball =  0x000f,
    cherishball =  0x0010,
    potion =  0x0011,
    antidote =  0x0012,
    burnheal =  0x0013,
    iceheal =  0x0014,
    awakening =  0x0015,
    parlyzheal =  0x0016,
    fullrestore =  0x0017,
    maxpotion =  0x0018,
    hyperpotion =  0x0019,
    superpotion =  0x001a,
    fullheal =  0x001b,
    revive =  0x001c,
    maxrevive =  0x001d,
    freshwater =  0x001e,
    sodapop =  0x001f,
    lemonade =  0x0020,
    moomoomilk =  0x0021,
    energypowder =  0x0022,
    energyroot =  0x0023,
    healpowder =  0x0024,
    revivalherb =  0x0025,
    ether =  0x0026,
    maxether =  0x0027,
    elixir =  0x0028,
    maxelixir =  0x0029,
    lavacookie =  0x002a,
    berryjuice =  0x002b,
    sacredash =  0x002c,
    hpup =  0x002d,
    protein =  0x002e,
    iron =  0x002f,
    carbos =  0x0030,
    calcium =  0x0031,
    rarecandy =  0x0032,
    ppup =  0x0033,
    zinc =  0x0034,
    ppmax =  0x0035,
    oldgateau =  0x0036,
    guardspec =  0x0037,
    direhit =  0x0038,
    xattack =  0x0039,
    xdefend =  0x003a,
    xspeed =  0x003b,
    xaccuracy =  0x003c,
    xspecial =  0x003d,
    xspdef =  0x003e,
    pokedoll =  0x003f,
    fluffytail =  0x0040,
    blueflute =  0x0041,
    yellowflute =  0x0042,
    redflute =  0x0043,
    blackflute =  0x0044,
    whiteflute =  0x0045,
    shoalsalt =  0x0046,
    shoalshell =  0x0047,
    redshard =  0x0048,
    blueshard =  0x0049,
    yellowshard =  0x004a,
    greenshard =  0x004b,
    superrepel =  0x004c,
    maxrepel =  0x004d,
    escaperope =  0x004e,
    repel =  0x004f,
    sunstone =  0x0050,
    moonstone =  0x0051,
    firestone =  0x0052,
    thunderstone =  0x0053,
    waterstone =  0x0054,
    leafstone =  0x0055,
    tinymushroom =  0x0056,
    bigmushroom =  0x0057,
    pearl =  0x0058,
    bigpearl =  0x0059,
    stardust =  0x005a,
    starpiece =  0x005b,
    nugget =  0x005c,
    heartscale =  0x005d,
    honey =  0x005e,
    growthmulch =  0x005f,
    dampmulch =  0x0060,
    stablemulch =  0x0061,
    gooeymulch =  0x0062,
    rootfossil =  0x0063,
    clawfossil =  0x0064,
    helixfossil =  0x0065,
    domefossil =  0x0066,
    oldamber =  0x0067,
    armorfossil =  0x0068,
    skullfossil =  0x0069,
    rarebone =  0x006a,
    shinystone =  0x006b,
    duskstone =  0x006c,
    dawnstone =  0x006d,
    ovalstone =  0x006e,
    oddkeystone =  0x006f,
    griseousorb =  0x0070,
    dousedrive =  0x0074,
    shockdrive =  0x0075,
    burndrive =  0x0076,
    chilldrive =  0x0077,
    sweetheart =  0x0086,
    adamantorb =  0x0087,
    lustrousorb =  0x0088,
    greetmail =  0x0089,
    favoredmail =  0x008a,
    rsvpmail =  0x008b,
    thanksmail =  0x008c,
    inquirymail =  0x008d,
    likemail =  0x008e,
    replymail =  0x008f,
    bridgemails =  0x0090,
    bridgemaild =  0x0091,
    bridgemailt =  0x0092,
    bridgemailv =  0x0093,
    bridgemailm =  0x0094,
    cheriberry =  0x0095,
    chestoberry =  0x0096,
    pechaberry =  0x0097,
    rawstberry =  0x0098,
    aspearberry =  0x0099,
    leppaberry =  0x009a,
    oranberry =  0x009b,
    persimberry =  0x009c,
    lumberry =  0x009d,
    sitrusberry =  0x009e,
    figyberry =  0x009f,
    wikiberry =  0x00a0,
    magoberry =  0x00a1,
    aguavberry =  0x00a2,
    iapapaberry =  0x00a3,
    razzberry =  0x00a4,
    blukberry =  0x00a5,
    nanabberry =  0x00a6,
    wepearberry =  0x00a7,
    pinapberry =  0x00a8,
    pomegberry =  0x00a9,
    kelpsyberry =  0x00aa,
    qualotberry =  0x00ab,
    hondewberry =  0x00ac,
    grepaberry =  0x00ad,
    tamatoberry =  0x00ae,
    cornnberry =  0x00af,
    magostberry =  0x00b0,
    rabutaberry =  0x00b1,
    nomelberry =  0x00b2,
    spelonberry =  0x00b3,
    pamtreberry =  0x00b4,
    watmelberry =  0x00b5,
    durinberry =  0x00b6,
    belueberry =  0x00b7,
    occaberry =  0x00b8,
    passhoberry =  0x00b9,
    wacanberry =  0x00ba,
    rindoberry =  0x00bb,
    yacheberry =  0x00bc,
    chopleberry =  0x00bd,
    kebiaberry =  0x00be,
    shucaberry =  0x00bf,
    cobaberry =  0x00c0,
    payapaberry =  0x00c1,
    tangaberry =  0x00c2,
    chartiberry =  0x00c3,
    kasibberry =  0x00c4,
    habanberry =  0x00c5,
    colburberry =  0x00c6,
    babiriberry =  0x00c7,
    chilanberry =  0x00c8,
    liechiberry =  0x00c9,
    ganlonberry =  0x00ca,
    salacberry =  0x00cb,
    petayaberry =  0x00cc,
    apicotberry =  0x00cd,
    lansatberry =  0x00ce,
    starfberry =  0x00cf,
    enigmaberry =  0x00d0,
    micleberry =  0x00d1,
    custapberry =  0x00d2,
    jabocaberry =  0x00d3,
    rowapberry =  0x00d4,
    brightpowder =  0x00d5,
    whiteherb =  0x00d6,
    machobrace =  0x00d7,
    expshare =  0x00d8,
    quickclaw =  0x00d9,
    soothebell =  0x00da,
    mentalherb =  0x00db,
    choiceband =  0x00dc,
    kingsrock =  0x00dd,
    silverpowder =  0x00de,
    amuletcoin =  0x00df,
    cleansetag =  0x00e0,
    souldew =  0x00e1,
    deepseatooth =  0x00e2,
    deepseascale =  0x00e3,
    smokeball =  0x00e4,
    everstone =  0x00e5,
    focusband =  0x00e6,
    luckyegg =  0x00e7,
    scopelens =  0x00e8,
    metalcoat =  0x00e9,
    leftovers =  0x00ea,
    dragonscale =  0x00eb,
    lightball =  0x00ec,
    softsand =  0x00ed,
    hardstone =  0x00ee,
    miracleseed =  0x00ef,
    blackglasses =  0x00f0,
    blackbelt =  0x00f1,
    magnet =  0x00f2,
    mysticwater =  0x00f3,
    sharpbeak =  0x00f4,
    poisonbarb =  0x00f5,
    nevermeltice =  0x00f6,
    spelltag =  0x00f7,
    twistedspoon =  0x00f8,
    charcoal =  0x00f9,
    dragonfang =  0x00fa,
    silkscarf =  0x00fb,
    upgrade =  0x00fc,
    shellbell =  0x00fd,
    seaincense =  0x00fe,
    laxincense =  0x00ff,
    luckypunch =  0x0100,
    metalpowder =  0x0101,
    thickclub =  0x0102,
    stick =  0x0103,
    redscarf =  0x0104,
    bluescarf =  0x0105,
    pinkscarf =  0x0106,
    greenscarf =  0x0107,
    yellowscarf =  0x0108,
    widelens =  0x0109,
    muscleband =  0x010a,
    wiseglasses =  0x010b,
    expertbelt =  0x010c,
    lightclay =  0x010d,
    lifeorb =  0x010e,
    powerherb =  0x010f,
    toxicorb =  0x0110,
    flameorb =  0x0111,
    quickpowder =  0x0112,
    focussash =  0x0113,
    zoomlens =  0x0114,
    metronome =  0x0115,
    ironball =  0x0116,
    laggingtail =  0x0117,
    destinyknot =  0x0118,
    blacksludge =  0x0119,
    icyrock =  0x011a,
    smoothrock =  0x011b,
    heatrock =  0x011c,
    damprock =  0x011d,
    gripclaw =  0x011e,
    choicescarf =  0x011f,
    stickybarb =  0x0120,
    powerbracer =  0x0121,
    powerbelt =  0x0122,
    powerlens =  0x0123,
    powerband =  0x0124,
    poweranklet =  0x0125,
    powerweight =  0x0126,
    shedshell =  0x0127,
    bigroot =  0x0128,
    choicespecs =  0x0129,
    flameplate =  0x012a,
    splashplate =  0x012b,
    zapplate =  0x012c,
    meadowplate =  0x012d,
    icicleplate =  0x012e,
    fistplate =  0x012f,
    toxicplate =  0x0130,
    earthplate =  0x0131,
    skyplate =  0x0132,
    mindplate =  0x0133,
    insectplate =  0x0134,
    stoneplate =  0x0135,
    spookyplate =  0x0136,
    dracoplate =  0x0137,
    dreadplate =  0x0138,
    ironplate =  0x0139,
    oddincense =  0x013a,
    rockincense =  0x013b,
    fullincense =  0x013c,
    waveincense =  0x013d,
    roseincense =  0x013e,
    luckincense =  0x013f,
    pureincense =  0x0140,
    protector =  0x0141,
    electirizer =  0x0142,
    magmarizer =  0x0143,
    dubiousdisc =  0x0144,
    reapercloth =  0x0145,
    razorclaw =  0x0146,
    razorfang =  0x0147,
    tm01 =  0x0148,
    tm02 =  0x0149,
    tm03 =  0x014a,
    tm04 =  0x014b,
    tm05 =  0x014c,
    tm06 =  0x014d,
    tm07 =  0x014e,
    tm08 =  0x014f,
    tm09 =  0x0150,
    tm10 =  0x0151,
    tm11 =  0x0152,
    tm12 =  0x0153,
    tm13 =  0x0154,
    tm14 =  0x0155,
    tm15 =  0x0156,
    tm16 =  0x0157,
    tm17 =  0x0158,
    tm18 =  0x0159,
    tm19 =  0x015a,
    tm20 =  0x015b,
    tm21 =  0x015c,
    tm22 =  0x015d,
    tm23 =  0x015e,
    tm24 =  0x015f,
    tm25 =  0x0160,
    tm26 =  0x0161,
    tm27 =  0x0162,
    tm28 =  0x0163,
    tm29 =  0x0164,
    tm30 =  0x0165,
    tm31 =  0x0166,
    tm32 =  0x0167,
    tm33 =  0x0168,
    tm34 =  0x0169,
    tm35 =  0x016a,
    tm36 =  0x016b,
    tm37 =  0x016c,
    tm38 =  0x016d,
    tm39 =  0x016e,
    tm40 =  0x016f,
    tm41 =  0x0170,
    tm42 =  0x0171,
    tm43 =  0x0172,
    tm44 =  0x0173,
    tm45 =  0x0174,
    tm46 =  0x0175,
    tm47 =  0x0176,
    tm48 =  0x0177,
    tm49 =  0x0178,
    tm50 =  0x0179,
    tm51 =  0x017a,
    tm52 =  0x017b,
    tm53 =  0x017c,
    tm54 =  0x017d,
    tm55 =  0x017e,
    tm56 =  0x017f,
    tm57 =  0x0180,
    tm58 =  0x0181,
    tm59 =  0x0182,
    tm60 =  0x0183,
    tm61 =  0x0184,
    tm62 =  0x0185,
    tm63 =  0x0186,
    tm64 =  0x0187,
    tm65 =  0x0188,
    tm66 =  0x0189,
    tm67 =  0x018a,
    tm68 =  0x018b,
    tm69 =  0x018c,
    tm70 =  0x018d,
    tm71 =  0x018e,
    tm72 =  0x018f,
    tm73 =  0x0190,
    tm74 =  0x0191,
    tm75 =  0x0192,
    tm76 =  0x0193,
    tm77 =  0x0194,
    tm78 =  0x0195,
    tm79 =  0x0196,
    tm80 =  0x0197,
    tm81 =  0x0198,
    tm82 =  0x0199,
    tm83 =  0x019a,
    tm84 =  0x019b,
    tm85 =  0x019c,
    tm86 =  0x019d,
    tm87 =  0x019e,
    tm88 =  0x019f,
    tm89 =  0x01a0,
    tm90 =  0x01a1,
    tm91 =  0x01a2,
    tm92 =  0x01a3,
    hm01 =  0x01a4,
    hm02 =  0x01a5,
    hm03 =  0x01a6,
    hm04 =  0x01a7,
    hm05 =  0x01a8,
    hm06 =  0x01a9,
    explorerkit =  0x01ac,
    lootsack =  0x01ad,
    rulebook =  0x01ae,
    pokeradar =  0x01af,
    pointcard =  0x01b0,
    journal =  0x01b1,
    sealcase =  0x01b2,
    fashioncase =  0x01b3,
    sealbag =  0x01b4,
    palpad =  0x01b5,
    workskey =  0x01b6,
    oldcharm =  0x01b7,
    galactickey =  0x01b8,
    redchain =  0x01b9,
    townmap =  0x01ba,
    vsseeker =  0x01bb,
    coincase =  0x01bc,
    oldrod =  0x01bd,
    goodrod =  0x01be,
    superrod =  0x01bf,
    sprayduck =  0x01c0,
    poffincase =  0x01c1,
    bicycle =  0x01c2,
    suitekey =  0x01c3,
    oaksletter =  0x01c4,
    lunarwing =  0x01c5,
    membercard =  0x01c6,
    azureflute =  0x01c7,
    ssticket =  0x01c8,
    contestpass =  0x01c9,
    magmastone =  0x01ca,
    parcel =  0x01cb,
    coupon1 =  0x01cc,
    coupon2 =  0x01cd,
    coupon3 =  0x01ce,
    storagekey =  0x01cf,
    secretpotion =  0x01d0,
    vsrecorder =  0x01d1,
    gracidea =  0x01d2,
    secretkey =  0x01d3,
    apricornbox =  0x01d4,
    unownreport =  0x01d5,
    berrypots =  0x01d6,
    dowsingmchn =  0x01d7,
    bluecard =  0x01d8,
    slowpoketail =  0x01d9,
    clearbell =  0x01da,
    cardkey =  0x01db,
    basementkey =  0x01dc,
    squirtbottle =  0x01dd,
    redscale =  0x01de,
    lostitem =  0x01df,
    pass =  0x01e0,
    machinepart =  0x01e1,
    silverwing =  0x01e2,
    rainbowwing =  0x01e3,
    mysteryegg =  0x01e4,
    redapricorn =  0x01e5,
    ylwapricorn =  0x01e6,
    bluapricorn =  0x01e7,
    grnapricorn =  0x01e8,
    pnkapricorn =  0x01e9,
    whtapricorn =  0x01ea,
    blkapricorn =  0x01eb,
    fastball =  0x01ec,
    levelball =  0x01ed,
    lureball =  0x01ee,
    heavyball =  0x01ef,
    loveball =  0x01f0,
    friendball =  0x01f1,
    moonball =  0x01f2,
    sportball =  0x01f3,
    parkball =  0x01f4,
    photoalbum =  0x01f5,
    gbsounds =  0x01f6,
    tidalbell =  0x01f7,
    ragecandybar =  0x01f8,
    datacard01 =  0x01f9,
    datacard02 =  0x01fa,
    datacard03 =  0x01fb,
    datacard04 =  0x01fc,
    datacard05 =  0x01fd,
    datacard06 =  0x01fe,
    datacard07 =  0x01ff,
    datacard08 =  0x0200,
    datacard09 =  0x0201,
    datacard10 =  0x0202,
    datacard11 =  0x0203,
    datacard12 =  0x0204,
    datacard13 =  0x0205,
    datacard14 =  0x0206,
    datacard15 =  0x0207,
    datacard16 =  0x0208,
    datacard17 =  0x0209,
    datacard18 =  0x020a,
    datacard19 =  0x020b,
    datacard20 =  0x020c,
    datacard21 =  0x020d,
    datacard22 =  0x020e,
    datacard23 =  0x020f,
    datacard24 =  0x0210,
    datacard25 =  0x0211,
    datacard26 =  0x0212,
    datacard27 =  0x0213,
    jadeorb =  0x0214,
    lockcapsule =  0x0215,
    redorb =  0x0216,
    blueorb =  0x0217,
    enigmastone =  0x0218,
    prismscale =  0x0219,
    eviolite =  0x021a,
    floatstone =  0x021b,
    rockyhelmet =  0x021c,
    airballoon =  0x021d,
    redcard =  0x021e,
    ringtarget =  0x021f,
    bindingband =  0x0220,
    absorbbulb =  0x0221,
    cellbattery =  0x0222,
    ejectbutton =  0x0223,
    firegem =  0x0224,
    watergem =  0x0225,
    electricgem =  0x0226,
    grassgem =  0x0227,
    icegem =  0x0228,
    fightinggem =  0x0229,
    poisongem =  0x022a,
    groundgem =  0x022b,
    flyinggem =  0x022c,
    psychicgem =  0x022d,
    buggem =  0x022e,
    rockgem =  0x022f,
    ghostgem =  0x0230,
    dragongem =  0x0231,
    darkgem =  0x0232,
    steelgem =  0x0233,
    normalgem =  0x0234,
    healthwing =  0x0235,
    musclewing =  0x0236,
    resistwing =  0x0237,
    geniuswing =  0x0238,
    cleverwing =  0x0239,
    swiftwing =  0x023a,
    prettywing =  0x023b,
    coverfossil =  0x023c,
    plumefossil =  0x023d,
    libertypass =  0x023e,
    passorb =  0x023f,
    dreamball =  0x0240,
    poketoy =  0x0241,
    propcase =  0x0242,
    dragonskull =  0x0243,
    balmmushroom =  0x0244,
    bignugget =  0x0245,
    pearlstring =  0x0246,
    cometshard =  0x0247,
    reliccopper =  0x0248,
    relicsilver =  0x0249,
    relicgold =  0x024a,
    relicvase =  0x024b,
    relicband =  0x024c,
    relicstatue =  0x024d,
    reliccrown =  0x024e,
    casteliacone =  0x024f,
    direhit2 =  0x0250,
    xspeed2 =  0x0251,
    xspecial2 =  0x0252,
    xspdef2 =  0x0253,
    xdefend2 =  0x0254,
    xattack2 =  0x0255,
    xaccuracy2 =  0x0256,
    xspeed3 =  0x0257,
    xspecial3 =  0x0258,
    xspdef3 =  0x0259,
    xdefend3 =  0x025a,
    xattack3 =  0x025b,
    xaccuracy3 =  0x025c,
    xspeed6 =  0x025d,
    xspecial6 =  0x025e,
    xspdef6 =  0x025f,
    xdefend6 =  0x0260,
    xattack6 =  0x0261,
    xaccuracy6 =  0x0262,
    abilityurge =  0x0263,
    itemdrop =  0x0264,
    itemurge =  0x0265,
    reseturge =  0x0266,
    direhit3 =  0x0267,
    lightstone =  0x0268,
    darkstone =  0x0269,
    tm93 =  0x026a,
    tm94 =  0x026b,
    tm95 =  0x026c,
    xtransceiver =  0x026d,
    godstone =  0x026e,
    gram1 =  0x026f,
    gram2 =  0x0270,
    gram3 =  0x0271,
    xtransceiver2 =  0x0272,
    medalbox =  0x0273,
    dnasplicers =  0x0274,
    dnasplicers2 =  0x0275,
    permit =  0x0276,
    ovalcharm =  0x0277,
    shinycharm =  0x0278,
    plasmacard =  0x0279,
    grubbyhanky =  0x027a,
    colressmchn =  0x027b,
    droppeditem =  0x027c,
    droppeditem2 =  0x027d,
    revealglass =  0x027e,
    weaknesspolicy=639,
    assaultvest=640,
    pixieplate=644,
    abilitycapsule=645,
    whippeddream=646,
    sachet=647,
    luminousmoss=648,
    snowball=649,
    safetygoggles=650,
    richmulch=652,
    surprisemulch=653,
    boostmulch=654,
    amazemulch=655,
    gengarite=656,
    gardevoirite=657,
    ampharosite=658,
    venusaurite=659,
    charizarditex=660,
    blastoisinite=661,
    mewtwonitex=662,
    mewtwonitey=663,
    blazikenite=664,
    medichamite=665,
    houndoominite=666,
    aggronite=667,
    banettite=668,
    tyranitarite=669,
    scizorite=670,
    pinsirite=671,
    aerodactylite=672,
    lucarionite=673,
    abomasite=674,
    kangashkanite=675,
    gyaradosite=676,
    absolite=677,
    charizarditey=678,
    alakazite=679,
    heracronite=680,
    mawilite=681,
    manectite=682,
    garchompite=683,
    roseliberry=686,
    keeberry=687,
    marangaberry=688,
    bargainticket=699,
    strangesouvenir=704,
    lumiosegalette=708,
    jawfossil=710,
    sailfossil=711,
    fairygem=715,
};
}
namespace Regions_3DS
{
enum regions : byte
{
    japan,
    usa,
    europe,
    cn=4,
    korea,
    tw
};
}
namespace Locations_g6
{
enum locations : uint16
{
    vanivilletown=0x0006,
    route1=0x0008,
    aquacordetown=0x000A,
    route2=0x000C,
    santaluneforest=0x000E,
    route3=0x0010,
    santalunecity=0x0012,
    route4=0x0014,
    lumiosecity=0x0016,
    lysandrelabs=0x001A,
    route5=0x001C,
    camphriertown=0x001E,
    route6=0x0022,
    parfumpalace=0x0024,
    route7=0x0026,
    cyllagecity=0x0028,
    route8=0x002A,
    ambrettetown=0x002C,
    route9=0x002E,
    battlechateau=0x0030,
    route10=0x0032,
    geosengetown=0x0034,
    route11=0x0036,
    reflectioncave=0x0038,
    shalourcity=0x003A,
    towerofmastery=0x003C,
    route12=0x003E,
    courmarinecity=0x0040,
    route13=0x0042,
    route14=0x0044,
    laverrecity=0x0046,
    pokeballfactory=0x0048,
    route15=0x004A,
    dendemilletown=0x004C,
    route16=0x004E,
    frostcavern=0x0052,
    route17=0x0054,
    anistarcity=0x0056,
    route18=0x0058,
    couriwaytown=0x005A,
    route19=0x005C,
    snowbellecity=0x005E,
    route20=0x0060,
    pokemonvillage=0x0062,
    route21=0x0064,
    route22=0x0066,
    victoryroad=0x0068,
    pokemonleague=0x006A,
    kiloudecity=0x006C,
    battlemaison=0x006E,
    azurebay=0x0070,
    glitteringcave=0x0084,
    connectingcave=0x0086,
    kalospowerplant=0x0088,
    teamflaresecrethq=0x008A,
    terminuscave=0x008C,
    losthotel=0x008E,
    champerofemptiness=0x0090,
    seaspiritsden=0x0092,
    friendsafari=0x0094,
    unknowndungeon=0x00A8,
    linktrade=0x7531,
    present=0x9C70,
    daycarecouple=0xEA62
};
}
namespace MegaEvolutions
{
/*
    0 = none, 1 = mega
Venusaur
Blastoise
Alakazam
Gengar
Kangaskhan
Pinsir
Gyarados
Aerodactyl
Ampharos
Scizor
Heracross
Houndoom
Tyranitar
Blaziken
Gardevoir
Mawile
Aggron
Medicham
Manetric
Banette
Absol
Garchomp
Lucario
Abomasnow

0 = none, 1 = x, 2 = y
Charizard
Mewtwo
    */
}
namespace Forms
{
namespace Vivillon
{
enum vivillon : byte
{
    icy_snow,
    polar,
    tundra,
    continental,
    garden,
    elegant,
    meadow,
    modern,
    marine,
    archipelago,
    high_plains,
    sandstorm,
    river,
    monsoon,
    savannah,
    sun,
    ocean,
    jungle
};
}
namespace Flabebe_Floette_Florges
{
enum flabebe_floette_florges : byte
{
    red_flower,
    yellow_flower,
    orange_flower,
    blue_flower,
    white_flower,
    eternal_flower // AZ's Floette
};
}
namespace Furfrou
{
enum furfrou : byte
{
    no_trim,
    heart_trim,
    star_trim,
    diamond_trim,
    debutante_trim,
    matron_trim,
    dandy_trim,
    la_reine_trim,
    kabuki_trim,
    pharoh_trim
};
}
namespace Meowstic
{
enum meowstic : byte
{
    male,
    female
};
}
namespace Aegislash
{
enum aegislash : byte
{
    shield,
    blade
};
}
namespace Pumpkaboo_Gourgeist
{
enum pumpkaboo_gourgeist : byte
{
    small_size,
    average_size,
    large_size,
    super_size
};
}
namespace Xerneas
{
enum xerneas : byte
{
    normal_mode,
    active_mode
};
}
}
struct kalosribbonsfield
{
    uint32 kaloschamp : 1;
    uint32 champion : 1;
    uint32 sinnohchamp : 1;
    uint32 bestfriends : 1;
    uint32 training : 1;
    uint32 skillfulbattler : 1;
    uint32 kalosribbon7 : 1;
    uint32 effort : 1;
    uint32 alert : 1;
    uint32 shock : 1;
    uint32 downcast : 1;
    uint32 careless : 1;
    uint32 relax : 1;
    uint32 snooze : 1;
    uint32 smile : 1;
    uint32 gorgeous : 1;
    uint32 royal : 1;
    uint32 gorgeousroyal : 1;
    uint32 artist : 1;
    uint32 footprint : 1;
    uint32 record : 1;
    uint32 legend : 1;
    uint32 country : 1;
    uint32 national : 1;
    uint32 earth : 1;
    uint32 world : 1;
    uint32 classic : 1;
    uint32 premier : 1;
    uint32 event_ : 1;
    uint32 birthday : 1;
    uint32 special : 1;
    uint32 festival : 1;
    byte wishing : 1;
    byte battle_champion : 1;
    byte regional_champion : 1;
    byte national_champion : 1;
    byte world_champion : 1;
    byte kalosribbon38 : 1;
    byte kalosribbon39 : 1;
    byte kalosribbon40 : 1;
    kalosribbonsfield()
    {
        memset(this,0,sizeof(kalosribbonsfield));
    }
};
struct supertrainingflags
{
    uint32 : 2;
    uint32 spatk1 : 1;
    uint32 hp1 : 1;
    uint32 atk1 : 1;
    uint32 spdef1 : 1;
    uint32 speed1 : 1;
    uint32 def1 : 1;
    uint32 spatk2 : 1;
    uint32 hp2 : 1;
    uint32 atk2 : 1;
    uint32 spdef2 : 1;
    uint32 speed2 : 1;
    uint32 def2 : 1;
    uint32 spatk3 : 1;
    uint32 hp3 : 1;
    uint32 atk3 : 1;
    uint32 spdef3 : 1;
    uint32 speed3 : 1;
    uint32 def3 : 1;
    uint32 secret1_1 : 1;
    uint32 secret1_2 : 1;
    uint32 secret1_3 : 1;
    uint32 secret1_4 : 1;
    uint32 secret1_5 : 1;
    uint32 secret1_6 : 1;
    uint32 secret2_1 : 1;
    uint32 secret2_2 : 1;
    uint32 secret2_3 : 1;
    uint32 secret2_4 : 1;
    uint32 secret2_5 : 1;
    uint32 secret2_6 : 1;
    supertrainingflags()
    {
        memset(this,0,sizeof(supertrainingflags));
    }
};
// http://projectpokemon.org/wiki/Pokemon_X/Y_3DS_Structure
//Unencrypted Data
struct pkxunencryptblock { // The unencrypted block of the Pokemon data, featuring such important things as the PID and checksum.
    uint32 key; // Used for encryption / decryption.
    uint16 ispartydatadecrypted : 1;
    uint16 isboxdatadecrypted : 1;
    uint16 isspeciesegg : 1;
    uint16 : 13;
    uint16 checksum; // The checksum for the Pokemon data; used to validate data.
    pkxunencryptblock()
    {
        memset(this,0,sizeof(pkxunencryptblock));
    }
};
struct pkxblocka { //
    Species_g6::pkxspecies species;
    Items_g6::items item;
    uint16 tid;
    uint16 sid;
    uint32 exp;
    Abilities_g6::abilities ability;
    byte abilitynum;
    uint16 : 16; // unknown
    uint32 pid;
    Natures::natures nature;
    formsfield forms;
    evsfield evs;
    contestfield contest;
    markingsfield markings;
    pokerus pkrs;
    supertrainingflags supertraining;
    kalosribbonsfield kalosribbons;
    uint16 : 16; // unused
    byte : 8; // unused
    byte contestribbons;
    byte battleribbons;
    byte unknown2[6]; // unused
    pkxblocka()
    {
        memset(this,0,sizeof(pkxblocka));
    }
};
struct pkxblockb { //
#if ! defined(MARKUP_SIZEOFWCHAR)
#if __SIZEOF_WCHAR_T__ == 4 || __WCHAR_MAX__ > 0x10000
    char nickname[24];
#else
    wchar_t nickname[12];
#endif
#endif
    uint16 : 16; // unused
    Moves_g6::moves moves[4];
    byte pp[4];
    byte ppup[4];
    Moves_g6::moves eggmoves[4];
    bool secretsupertraining : 8;
    byte : 8; // unused
    ivsfield ivs;
    pkxblockb()
    {
        memset(this,0,sizeof(pkxblockb));
    }
};
struct pkxblockc { //
#if ! defined(MARKUP_SIZEOFWCHAR)
#if __SIZEOF_WCHAR_T__ == 4 || __WCHAR_MAX__ > 0x10000
    char otname_to[24];
#else
    wchar_t otname_to[12];
#endif
#endif
    uint16 : 16; // unused
    uint16 : 16; // 00/01 flags
    uint16 geolocation_1;
    uint16 geolocation_2;
    uint16 geolocation_3;
    uint16 geolocation_4;
    uint16 geolocation_5;
    uint16 : 16; // unused
    uint16 : 16; // unused
    byte previous_tameness;
    byte previous_affection;
    byte : 8; // previous text bank
    byte : 8; // previous text line
    byte previous_feeling;
    byte : 8; // unused
    uint16 : 16; // previous memory text var
    uint16 : 16; // unused
    uint16 : 16; // unused
    byte fullness;
    byte enjoyment;
    pkxblockc()
    {
        memset(this,0,sizeof(pkxblockc));
    }
};
struct pkxblockd { // 
#if ! defined(MARKUP_SIZEOFWCHAR)
#if __SIZEOF_WCHAR_T__ == 4 || __WCHAR_MAX__ > 0x10000
    char otname[24];
#else
    wchar_t otname[12];
#endif
#endif
    uint16 : 16; // unused
    byte tameness;
    byte affection;
    byte : 8; // memory text bank
    byte : 8; // memory text line
    uint16 : 16; // memory text var
    byte : 8; // feeling
    datefield eggdate;
    datefield metdate;
    byte : 8; // Unknown / unused
    Locations_g6::locations eggmet;
    Locations_g6::locations met;
    Balls::balls ball;
    metlevelfield metlevel_otgender;
    Encounters::encounters encounter;
    Hometowns::hometowns hometown;
    byte country;
    byte regionid;
    Regions_3DS::regions regionid3ds;
    Countries::countries otlang;
    uint32 : 32; // unused
    pkxblockd()
    {
        memset(this,0,sizeof(pkxblockd));
    }
};
struct pokemonx_obj : pkxunencryptblock,pkxblocka,pkxblockb,pkxblockc,pkxblockd { // The Pokemon object, containing 232 bytes of data (as stored in the PC storage system)
    pokemonx_obj()
    {
        memset(this,0,sizeof(pokemonx_obj));
    }
};
struct partyx_field { // Size: 
    status_field status;
    byte : 8;
    uint16 : 16;
    byte level;
    uint16 : 16;
    byte : 8;
    uint16 hp;
    uint16 maxhp;
    uint16 attack;
    uint16 defense;
    uint16 speed;
    uint16 spatk;
    uint16 spdef;
    uint16 : 16;
    uint32 : 32;
    partyx_field()
    {
        memset(this,0,sizeof(partyx_field));
    }
};
struct party_pkx : pokemonx_obj { // Size:
    //    pokemonx_obj pkx_data;
    partyx_field party_data;
    party_pkx()
    {
        memset(this,0,sizeof(party_pkx));
    }
};
struct xybox
{
    pokemonx_obj pokemon[30];
};
struct xysavehalf // size 0x69000
{
    //byte unknown1[0x27A00];
    byte unknown1[0x25A00];
    xybox boxes[31];
    //    byte unknown2[0xCB30];
    byte unknown2[0xEB30];
};
struct xysavefile
{
    byte image_header[0x45B];
    byte unknown1[0xBA5];
    byte first_partition[0x107];
    byte unknown2[0xEF9];
    xysavehalf sav1; // size 0x69000
    byte unknown3[0x16000];
    xysavehalf sav2; // size 0x69000
    byte unknown4[0x16000];
};
void DllExport pkmcrypt(partyx_field* pkx, uint32 pid);
void DllExport encryptpkm(party_pkx* pkx);
void DllExport decryptpkm(party_pkx* pkx);
byte DllExport getpkmshuffleindex(const pokemonx_obj *pkx);
void DllExport unshufflepkm(pokemonx_obj *pkx);
void DllExport shufflepkm(pokemonx_obj *pkx);
void DllExport pkmcrypt(pokemonx_obj* pkx);
void DllExport encryptpkm(pokemonx_obj* pkx);
void DllExport decryptpkm(pokemonx_obj* pkx);
void DllExport calcchecksum(pokemonx_obj* pkx);
void DllExport read(const char* file_name, pokemonx_obj *data);
void DllExport read(const char* file_name, xysavefile *data);
#ifdef _MSC_VER
void DllExport read(const wchar_t * file_name, pokemonx_obj *data);
#endif
void DllExport write(const char* file_name, pokemonx_obj* data);
#ifdef _MSC_VER
void DllExport write(const wchar_t * file_name, pokemonx_obj* data);
#endif
bool DllExport getpkmshiny(const pokemonx_obj *pkx);
int DllExport getchecksum(pokemonx_obj* pkx);
